### ISSUE TITLE
fatal error: mlock failed

### ISSUE THREAD

**Issue by luvs** [Vertamedia/chproxy#124]
My chproxy fails every 10-20 minutes with error (without any incoming requests)

```
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime: mlock of signal stack failed: 12
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime: increase the mlock limit (ulimit -l) or
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: fatal error: mlock failed
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime stack:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.throw(0x9d7180, 0xc)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/panic.go:1112 +0x72
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.mlockGsignal(0xc00022e300)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/os_linux_x86.go:72 +0x107
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.mpreinit(0xc000148000)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/os_linux.go:341 +0x78
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.mcommoninit(0xc000148000)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:630 +0x108
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.allocm(0xc000047000, 0x9fc338, 0x6638f009eb289f)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:1390 +0x14e
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.newm(0x9fc338, 0xc000047000)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:1704 +0x39
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.startm(0x0, 0xc000282a01)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:1869 +0x12a
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.wakep(...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:1953
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.resetspinning()
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:2415 +0x93
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.schedule()
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:2527 +0x2de
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.park_m(0xc00030d080)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/proc.go:2690 +0x9d
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: runtime.mcall(0x800000)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/asm_amd64.s:318 +0x5b
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 1 [select (no cases), 14 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.main()
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:86 +0x7c4
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 13 [select, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).getConn(0xf96f20, 0xc0001dcba0, 0x0, 0xc00002b530, 0x4, 0xc0001bcf50, 0xf, 0x0, 0x0, 0x0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1291 +0x57b
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).roundTrip(0xf96f20, 0xc0001ca900, 0xc000193650, 0xc000359980, 0x417a98)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:552 +0x726
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).RoundTrip(0xf96f20, 0xc0001ca900, 0xf96f20, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/roundtrip.go:17 +0x35
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.send(0xc0001ca900, 0xa85060, 0xf96f20, 0x0, 0x0, 0x0, 0xc00048e2c8, 0x203000, 0x1, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/client.go:252 +0x43e
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Client).send(0xfeda00, 0xc0001ca900, 0x0, 0x0, 0x0, 0xc00048e2c8, 0x0, 0x1, 0x10)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/client.go:176 +0xfa
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Client).do(0xfeda00, 0xc0001ca900, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/client.go:699 +0x44a
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Client).Do(...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/client.go:567
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*heartBeat).isHealthy(0xc00007ca50, 0xc0001fe420, 0x16, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/heartbeat.go:47 +0x259
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*host).runHeartbeat.func1()
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/scope.go:639 +0x57
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*host).runHeartbeat(0xc000218240, 0xc00007e180)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/scope.go:654 +0x1e6
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*reverseProxy).applyConfig.func2(0xc000194120, 0xc000218240)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:403 +0x39
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.(*reverseProxy).applyConfig
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:402 +0x761
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 14 [select, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*host).runHeartbeat(0xc000218260, 0xc00007e180)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/scope.go:650 +0x271
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*reverseProxy).applyConfig.func2(0xc000194120, 0xc000218260)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:403 +0x39
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.(*reverseProxy).applyConfig
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:402 +0x761
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 15 [select, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*rateLimiter).run(0xc00002cf34, 0xc00007e180)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/scope.go:873 +0xc1
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*reverseProxy).applyConfig.func3(0xc000194120, 0xc00002cf00)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:411 +0x3f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.(*reverseProxy).applyConfig
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:410 +0x87e
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 16 [select, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*rateLimiter).run(0xc000117f94, 0xc00007e180)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/scope.go:873 +0xc1
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.(*reverseProxy).applyConfig.func4(0xc000194120, 0xc000117f40)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:419 +0x3f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.(*reverseProxy).applyConfig
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/proxy.go:418 +0x99d
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 50 [syscall, 14 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: os/signal.signal_recv(0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/sigqueue.go:147 +0x9c
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: os/signal.loop()
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/os/signal/signal_unix.go:23 +0x22
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by os/signal.Notify.func1
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/os/signal/signal.go:127 +0x44
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 52 [chan receive, 14 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.main.func1(0xc00007e240)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:59 +0x41
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.main
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:57 +0x66c
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 53 [IO wait, 14 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.runtime_pollWait(0x7f7e80423d88, 0x72, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/netpoll.go:203 +0x55
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*pollDesc).wait(0xc000158918, 0x72, 0x0, 0x0, 0x9d5509)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:87 +0x45
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*pollDesc).waitRead(...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:92
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*FD).Accept(0xc000158900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_unix.go:384 +0x1d4
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*netFD).accept(0xc000158900, 0xc000063cf0, 0xc000088000, 0x7f7ea80f2108)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/fd_unix.go:238 +0x42
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*TCPListener).accept(0xc0002194a0, 0xc000063d30, 0x417a98, 0x30)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/tcpsock_posix.go:139 +0x32
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*TCPListener).Accept(0xc0002194a0, 0x999e40, 0xc0002175c0, 0x945e40, 0xf8ec80)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/tcpsock.go:261 +0x64
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Server).Serve(0xc000212540, 0xa8cee0, 0xc0002194a0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/server.go:2901 +0x25d
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.listenAndServe(0xa8cee0, 0xc0002194a0, 0xa85b60, 0x9fbbc8, 0xdf8475800, 0xdf8475800, 0x8bb2c97000, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:194 +0xc5
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: main.serve(0xc0000253a0, 0xc, 0xc00000ffc0, 0x2, 0x2, 0xc000218220, 0x4, 0x4, 0x0, 0xdf8475800, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:153 +0x236
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by main.main
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/chproxy/main.go:83 +0x727
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 1977 [select, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*persistConn).writeLoop(0xc0002c5440)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:2277 +0x11c
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by net/http.(*Transport).dialConn
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1648 +0xc7b
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 1976 [IO wait, 2 minutes]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.runtime_pollWait(0x7f7e80423e68, 0x72, 0xffffffffffffffff)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/runtime/netpoll.go:203 +0x55
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*pollDesc).wait(0xc0001ce598, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:87 +0x45
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*pollDesc).waitRead(...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:92
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*FD).Read(0xc0001ce580, 0xc000342000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_unix.go:169 +0x19b
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*netFD).Read(0xc0001ce580, 0xc000342000, 0x1000, 0x1000, 0x44116c, 0xc000350b70, 0x46ad20)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/fd_unix.go:202 +0x4f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*conn).Read(0xc0000a63a0, 0xc000342000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/net.go:184 +0x8e
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*persistConn).Read(0xc0002c5440, 0xc000342000, 0x1000, 0x1000, 0xc00033e360, 0xc000350c70, 0x4100b5)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1825 +0x75
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: bufio.(*Reader).fill(0xc0004374a0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/bufio/bufio.go:100 +0x103
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: bufio.(*Reader).Peek(0xc0004374a0, 0x1, 0x0, 0x0, 0x1, 0xc00033e200, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/bufio/bufio.go:138 +0x4f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*persistConn).readLoop(0xc0002c5440)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1978 +0x1a8
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by net/http.(*Transport).dialConn
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1647 +0xc56
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: goroutine 1966 [runnable]:
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.setDeadlineImpl(0xc0001ed600, 0xc03cc0fc5ec8db08, 0x1113bc8c862, 0xfedc60, 0x77, 0x0, 0xc0000db168)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:140 +0x205
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: internal/poll.(*FD).SetWriteDeadline(...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/internal/poll/fd_poll_runtime.go:137
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*netFD).connect(0xc0001ed600, 0xa8e4a0, 0xc00028f9e0, 0x0, 0x0, 0xa854a0, 0xc00048b180, 0x0, 0x0, 0x0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/fd_unix.go:100 +0x68f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*netFD).dial(0xc0001ed600, 0xa8e4a0, 0xc00028f9e0, 0xa90920, 0x0, 0xa90920, 0xc000249530, 0x0, 0xa75b01, 0xc0000db410)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/sock_posix.go:149 +0xff
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.socket(0xa8e4a0, 0xc00028f9e0, 0x9d4890, 0x3, 0x2, 0x1, 0x0, 0x0, 0xa90920, 0x0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/sock_posix.go:70 +0x1c0
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.internetSocket(0xa8e4a0, 0xc00028f9e0, 0x9d4890, 0x3, 0xa90920, 0x0, 0xa90920, 0xc000249530, 0x1, 0x0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/ipsock_posix.go:141 +0x141
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*sysDialer).doDialTCP(0xc0001ed580, 0xa8e4a0, 0xc00028f9e0, 0x0, 0xc000249530, 0x94f960, 0x1018a40, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/tcpsock_posix.go:65 +0xc2
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*sysDialer).dialTCP(0xc0001ed580, 0xa8e4a0, 0xc00028f9e0, 0x0, 0xc000249530, 0x9d4866, 0x3, 0x10)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/tcpsock_posix.go:61 +0xd7
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*sysDialer).dialSingle(0xc0001ed580, 0xa8e4a0, 0xc00028f9e0, 0xa88b60, 0xc000249530, 0x0, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/dial.go:581 +0x60a
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*sysDialer).dialSerial(0xc0001ed580, 0xa8e4a0, 0xc00028f9e0, 0xc00023ce50, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/dial.go:549 +0x14f
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net.(*Dialer).DialContext(0xc00002c2a0, 0xa8e4a0, 0xc00028f9e0, 0x9d4890, 0x3, 0xc0001bcf50, 0xf, 0x0, 0x0, 0x0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/dial.go:426 +0x6d8
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).dial(0xf96f20, 0xa8e4a0, 0xc00028f9e0, 0x9d4890, 0x3, 0xc0001bcf50, 0xf, 0x0, 0x4483e8, 0xc0000bea80, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1085 +0x1f5
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).dialConn(0xf96f20, 0xa8e4a0, 0xc00028f9e0, 0x0, 0xc00002b530, 0x4, 0xc0001bcf50, 0xf, 0x0, 0xc00011cea0, ...)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1519 +0x19ee
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: net/http.(*Transport).dialConnFor(0xf96f20, 0xc00012b1e0)
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1365 +0xc6
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]: created by net/http.(*Transport).queueForDial
Aug 10 14:25:50 front-2-vin1 chproxy[2119066]:         /home/valyala/work/go-src/src/net/http/transport.go:1334 +0x3fe
Aug 10 14:25:50 front-2-vin1 systemd[1]: chproxy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 10 14:25:50 front-2-vin1 systemd[1]: chproxy.service: Failed with result 'exit-code'.
Aug 10 14:25:53 front-2-vin1 systemd[1]: chproxy.service: Scheduled restart job, restart counter is at 93.
Aug 10 14:25:53 front-2-vin1 systemd[1]: Stopped ClickHouse Proxy Service.
Aug 10 14:25:53 front-2-vin1 systemd[1]: Started ClickHouse Proxy Service.
Aug 10 14:25:53 front-2-vin1 chproxy[2132132]: INFO: 2021/08/10 14:25:53 main.go:44: chproxy ver. v1.14.0, rev. ea4d0666ea374b8969cc4b5956d8d6c3aff11c20, built at 2020-02-05_20:08:40
Aug 10 14:25:53 front-2-vin1 chproxy[2132132]: INFO: 2021/08/10 14:25:53 main.go:45: Loading config: /etc/chproxy/config.yml
```

mlock limit
```
chproxy@front-2-vin1:/etc/chproxy$ ulimit -l
65536
```

**Comment by vfoucault** [comment]
Hi there, the is a known issue with some linux distros. Try to upgrade your kernel / update your distribution if the ulimit thing does not work. Besides that, not related to chproxy itself.

**Comment by luvs** [comment]
@vfoucault thanks. Kernel update fix that.
