### ISSUE TITLE
Connection exception

### ISSUE THREAD

**Issue by AntonKuzValid** [Vertamedia/chproxy#44]
I'm using jdbc client written on on java. When i use a long-time query i got this exception - 
```
Caused by: java.sql.SQLException: org.apache.http.TruncatedChunkException: Truncated chunk ( expected size: 4096; actual size: 4088)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:129)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:143)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:93)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
	... 45 more
Caused by: org.apache.http.TruncatedChunkException: Truncated chunk ( expected size: 4096; actual size: 4088)
	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:198)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at com.google.common.io.ByteStreams.read(ByteStreams.java:859)
	at com.google.common.io.ByteStreams.readFully(ByteStreams.java:738)
	at com.google.common.io.ByteStreams.readFully(ByteStreams.java:722)
	at com.google.common.io.LittleEndianDataInputStream.readFully(LittleEndianDataInputStream.java:65)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.readNextBlock(ClickHouseLZ4Stream.java:101)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.checkNext(ClickHouseLZ4Stream.java:74)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.read(ClickHouseLZ4Stream.java:60)
	at ru.yandex.clickhouse.response.StreamSplitter.readFromStream(StreamSplitter.java:92)
	at ru.yandex.clickhouse.response.StreamSplitter.next(StreamSplitter.java:54)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:116)
```
Here is my congif - 

```log_debug: true

hack_me_please: true
server:
  http:
    listen_addr: ":9090"
    read_timeout: 50m

users:
  - name: ""
    password: ""
    to_cluster: ""
    to_user: ""

clusters:
  - name: ""
    nodes: []
```
I also tried the same query directly to database and it works fine

**Comment by artiship** [comment]
the same error

**Comment by AntonKuzValid** [comment]
For me the solution was to add to config file - max_execution_time: 10m. In some reasons when i didn't specify this option - i got EOF on  my client and 499 http exception in proxy

**Comment by artiship** [comment]
Yes, we config max_execution_time: 5m, and should also increase read_timeout, but modify configurations of sever section should restart, kill by signup to reload config not work

**Comment by hagen1778** [comment]
Closing this issue due to inactivity. Feel free to reopen.

**Comment by songlingling0012** [comment]
I met the same error ,and the config of max_execution_time\read_timeout didn't make sense

**Comment by songlingling0012** [comment]
I met the same error ,but the config of max_execution_time\read_timeout didn't make sense
